module.exports = {
  'cube': require('./cube/rotation.js'),
  'cuboctahedron': require('./cuboctahedron/rotation.js'),
  'dodecahedron': require('./dodecahedron/rotation.js'),
  'icosahedron': require('./icosahedron/rotation.js'),
  'icosidodecahedron': require('./icosidodecahedron/rotation.js'),
  'octahedron': require('./octahedron/rotation.js'),
  'rhombicosidodecahedron': require('./rhombicosidodecahedron/rotation.js'),
  'rhombicuboctahedron': require('./rhombicuboctahedron/rotation.js'),
  'snub-cube': require('./snub-cube/rotation.js'),
  'snub-dodecahedron': require('./snub-dodecahedron/rotation.js'),
  'tetrahedron': require('./tetrahedron/rotation.js'),
  'truncated-cube': require('./truncated-cube/rotation.js'),
  'truncated-cuboctahedron': require('./truncated-cuboctahedron/rotation.js'),
  'truncated-dodecahedron': require('./truncated-dodecahedron/rotation.js'),
  'truncated-icosahedron': require('./truncated-icosahedron/rotation.js'),
  'truncated-icosidodecahedron': require('./truncated-icosidodecahedron/rotation.js'),
  'truncated-octahedron': require('./truncated-octahedron/rotation.js'),
  'truncated-tetrahedron': require('./truncated-tetrahedron/rotation.js')
};
